#------------------------------------------------------------------------------
# Checks out the neonFORGE GitHub repos to a JOBRUNNER within the [C:\src] directory.
#
# This currently manages the following neonFORGE repos:
#
#   neonCLOUD           - private/enterprise code including deployment scripts
#   neonKUBE            - public neonKUBE related code
#   neonLIBRARY         - public neonLIBRARY related code
#   nforgeio.github.io  - public neonLIBRARY code documentation (doc.neonforge.com)
#   cadence-samples     - public Cadence sample apps
#   temporal-samples    - public Temporal sample apps
#
# NOTE: Only the neonCLOUD repos includes GitHub actions.

name: neon-pull-repos
description: Checks out the neonCLOUD, neonKUBE, and neonLIBRARY repos.
inputs:
  branch:
    description: Optionally specifies the branch or tag (defaults to "master")
    required: false
    default: master
runs:
  using: composite
  steps:
  - name: checkout-all
    shell: pwsh
    run: |
      
      # Checks out the named repo, resetting it first to clear
      # any uncommitted changes.
      function Checkout
      {
          [CmdletBinding()]
          param (
              [Parameter(Position=0, Mandatory=1)]
              [string]$repoName
          )
          
          $repoPath = "$env:NF_REPOS\$repoName"
          
          Write-Output ""
          Write-Output "Checkout: $repoPath"
            
          Push-Location $repoPath
          
          git reset --hard
          git checkout "$env:branch"
          
          Pop-Location
      }
        
      # Checkout the repos
        
      Checkout neonCLOUD
      Checkout neonKUBE
      Checkout neonLIBRARY
      Checkout nforgeio.github.io
      Checkout cadence-samples
      Checkout temporal-samples
