#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC.

#------------------------------------------------------------------------------
# Checks out the neonFORGE GitHub repos to a JOBRUNNER within the [C:\src] directory.
#
# This currently manages the following neonFORGE repos:
#
#   neonCLOUD           - private/enterprise code including deployment scripts
#   neonKUBE            - public neonKUBE related code
#   neonLIBRARY         - public neonLIBRARY related code
#   nforgeio.github.io  - public neonLIBRARY code documentation (doc.neonforge.com)
#   cadence-samples     - public Cadence sample apps
#   temporal-samples    - public Temporal sample apps

name: checkout
description: Checks out the neonFORGE repos.
inputs:
  branch:
    description: Optionally specifies the branch or tag (defaults to "master")
    required: false
    default: master
runs:
  using: node12
  main: action.js
